export type SitePage = {
  path: string;
  title: string;
  subtitle: string;
  section: "home" | "core" | "verification" | "engineering" | "reference" | "audit";
  chapters: string[];
  dependsOn: SitePage["path"][];
  storyOrder?: 1 | 2 | 3 | 4;
  storyLabel?: "소개" | "핵심 아이디어" | "참고자료" | "내용 검증";
};

export const SITE_PAGES: SitePage[] = [
  {
    path: "/",
    title: "Home",
    subtitle: "SALT 검증 콘솔의 첫 진입점과 전체 요약",
    section: "home",
    chapters: ["00장", "18장", "19장"],
    dependsOn: [],
    storyOrder: 1,
    storyLabel: "소개",
  },
  {
    path: "/core",
    title: "Core",
    subtitle: "이론 코어와 17장 중심 개념",
    section: "core",
    chapters: ["06장", "12장", "17장"],
    dependsOn: ["/"],
    storyOrder: 2,
    storyLabel: "핵심 아이디어",
  },
  {
    path: "/core/logic-map",
    title: "Core Logic Map",
    subtitle: "Problem에서 Verification까지 이어지는 논리 중간층",
    section: "core",
    chapters: ["12장", "17장", "18장", "21장"],
    dependsOn: ["/core"],
    storyOrder: 2,
    storyLabel: "핵심 아이디어",
  },
  {
    path: "/core/chapters",
    title: "Core Chapters",
    subtitle: "17·18·19장 중심 장별 압축 허브",
    section: "core",
    chapters: ["17장", "18장", "19장"],
    dependsOn: ["/core"],
    storyOrder: 2,
    storyLabel: "핵심 아이디어",
  },
  {
    path: "/core/chapters/[chapter]",
    title: "Core Chapter Detail",
    subtitle: "핵심 장별 상세 요약 페이지",
    section: "core",
    chapters: ["17장", "18장", "19장"],
    dependsOn: ["/core/chapters"],
    storyOrder: 2,
    storyLabel: "핵심 아이디어",
  },
  {
    path: "/verification",
    title: "Verification",
    subtitle: "검증 채널 개요와 현재 판정 상태",
    section: "verification",
    chapters: ["18장", "27장"],
    dependsOn: ["/", "/core"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/verification/channels",
    title: "Verification Channels",
    subtitle: "고정 검증 채널 인덱스",
    section: "verification",
    chapters: ["18장", "26장"],
    dependsOn: ["/verification"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/verification/channels/[channel]",
    title: "Verification Channel Detail",
    subtitle: "개별 고정 채널의 관측량, 기준선, 기각 조건",
    section: "verification",
    chapters: ["18장", "26장"],
    dependsOn: ["/verification/channels"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/verification/results",
    title: "Verification Results",
    subtitle: "고정 채널별 승패와 세부 판정 결과",
    section: "verification",
    chapters: ["18장", "27장"],
    dependsOn: ["/verification"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/verification/pending",
    title: "Verification Pending",
    subtitle: "운영 잠금 전 후보 가설과 검증 대기 항목",
    section: "verification",
    chapters: ["20장", "27장"],
    dependsOn: ["/verification"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/verification/candidate-hypotheses",
    title: "Candidate Hypotheses",
    subtitle: "판정 규칙 잠금 전 검증 대기 가설 인덱스",
    section: "verification",
    chapters: ["20장", "27장"],
    dependsOn: ["/verification"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/engineering",
    title: "Engineering",
    subtitle: "공학적 함의와 설계 가설",
    section: "engineering",
    chapters: ["19장"],
    dependsOn: ["/verification"],
    storyOrder: 2,
    storyLabel: "핵심 아이디어",
  },
  {
    path: "/reference",
    title: "Reference",
    subtitle: "도해, 용어, FAQ, 책 구조도",
    section: "reference",
    chapters: ["21장", "24장", "28장"],
    dependsOn: ["/", "/core", "/verification"],
    storyOrder: 3,
    storyLabel: "참고자료",
  },
  {
    path: "/reference/book-map",
    title: "Book Map",
    subtitle: "책 장 구조와 웹 구조의 대응표",
    section: "reference",
    chapters: ["00장", "17장", "18장", "19장", "21장", "28장"],
    dependsOn: ["/reference"],
    storyOrder: 3,
    storyLabel: "참고자료",
  },
  {
    path: "/reference/faq",
    title: "FAQ",
    subtitle: "자주 묻는 질문과 주요 쟁점 정리",
    section: "reference",
    chapters: ["20장", "21장"],
    dependsOn: ["/reference"],
    storyOrder: 3,
    storyLabel: "참고자료",
  },
  {
    path: "/reference/glossary",
    title: "Glossary",
    subtitle: "주요 용어와 개념 관계 정리",
    section: "reference",
    chapters: ["12장", "17장", "22장"],
    dependsOn: ["/reference"],
    storyOrder: 3,
    storyLabel: "참고자료",
  },
  {
    path: "/reference/visual-atlas",
    title: "Visual Atlas",
    subtitle: "도해와 그래프를 맥락 단위로 묶은 참고 페이지",
    section: "reference",
    chapters: ["17장", "18장", "19장", "21장"],
    dependsOn: ["/reference"],
    storyOrder: 3,
    storyLabel: "참고자료",
  },
  {
    path: "/discussion",
    title: "Discussion",
    subtitle: "방문자 토론과 질문을 모으는 공개 게시판",
    section: "reference",
    chapters: ["21장"],
    dependsOn: ["/"],
    storyOrder: 1,
    storyLabel: "소개",
  },
  {
    path: "/audit",
    title: "Audit",
    subtitle: "재현성과 provenance 허브",
    section: "audit",
    chapters: ["24장", "25장", "26장", "27장"],
    dependsOn: ["/verification"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/reproduce",
    title: "Audit Reproduce",
    subtitle: "재현 절차와 잠금 해시 검증",
    section: "audit",
    chapters: ["26장", "27장", "28장"],
    dependsOn: ["/verification/results"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/comments",
    title: "Audit Moderation",
    subtitle: "댓글 신고, 최근 댓글, 운영 액션 이력",
    section: "audit",
    chapters: ["18장", "19장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/datasets",
    title: "Audit Datasets",
    subtitle: "고정 데이터셋과 버전 정보",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/formulas",
    title: "Audit Formulas",
    subtitle: "사용 중인 공식 버전과 비교식",
    section: "audit",
    chapters: ["24장", "26장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/sources",
    title: "Audit Sources",
    subtitle: "출처와 입력 데이터 계보",
    section: "audit",
    chapters: ["24장", "27장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/audit/runs",
    title: "Audit Runs",
    subtitle: "실행 단위와 잠금 결과 요약",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/runs",
    title: "Runs",
    subtitle: "published snapshot 기준 최신 run provenance",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/audit/runs"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/runs/[runId]",
    title: "Run Detail",
    subtitle: "개별 실행 provenance 상세",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/runs"],
  },
  {
    path: "/snapshots",
    title: "Snapshots",
    subtitle: "snapshot provenance 인덱스",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/audit"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/snapshots/[snapshotId]",
    title: "Snapshot Detail",
    subtitle: "개별 snapshot 상세와 연결 run 정보",
    section: "audit",
    chapters: ["26장", "27장"],
    dependsOn: ["/snapshots"],
    storyOrder: 4,
    storyLabel: "내용 검증",
  },
  {
    path: "/notice",
    title: "Notice",
    subtitle: "운영 공지와 안내",
    section: "home",
    chapters: ["00장"],
    dependsOn: ["/"],
    storyOrder: 1,
    storyLabel: "소개",
  },
];

export const PAGE_INDEX = Object.fromEntries(SITE_PAGES.map((p) => [p.path, p]));
